### ISSUE TITLE
How to reassemble decrypted .ncch partition files back into a .3ds file?

### ISSUE THREAD

**Issue by udance4ever** [shijimasoft/cia-unix#18]
Hi! There’s no discussion tab so apologies for posting this question as an issue.

I have your [experimental](https://github.com/shijimasoft/cia-unix/tree/experimental) python3 script working in Batocera Linux in a virtualenv.

giving it an encrypted .3ds file it writes a `.Main.ncch`, `.Manual.ncch`, `.N3DSUpdateData.ncch` and `.UpdateData.ncch` files which I assume are the extracted partitions.

Do I use another command to reassemble the decrypted partitions into a .3ds file again?

I tried to download `makerom` but couldn’t make heads or tails of the usage.

**Comment by ibyrd1** [comment]
I'm wondering the same thing as @udance4ever . I'm fairly new to ROMs so I'm not sure what these files are or if they are needed for the game to work now.

**Comment by udance4ever** [comment]
@ibyrd1 welcome to the adventure! 🥾

until we get some input into what .ncch files are - this utility works great in Python 2.7:

https://github.com/b1k/b3DS

I am still hoping to use cia-unix as it is actively being maintained with support for Python3!

**Comment by shijimasoft** [comment]
Thank you for posting this question.
The `decrypt.py` file is only a module of the cia-unix program, so it was not designed to run independently.
To decrypt and recompress a `.3ds` file, you should run the `./cia-unix` command **in the same folder where the ROM is located** (along with the necessary modules: `makerom`, `ctrtool`, and `decrypt.py`).
cia-unix will take care of the whole process and if any dependencies are missing it will ask you to install them (by running the dltools.sh file, make sure it has run permissions with `chmod +x dltools.sh`)

About the python3 version: it is still in slow development, but thanks to the github community it has made a lot of progress..
The goal is to make all modules native (which is why I'm rewriting the[ decrypt.py module in rust](https://github.com/shijimasoft/ctrdecrypt)) so installing dependencies will become much easier in the future.

**Comment by shijimasoft** [comment]
Can I consider the issue solved ?

**Comment by shijimasoft** [comment]
I will close the issue, if you have other problems related to that, please write them in this issue pinging me. Thank you :)

**Comment by udance4ever** [comment]
oh!  no problem.  yes, consider this issue closed (I will be sure to do this next time a question I ask is answered).

Next I need to decrypt a .3ds file, I will make a point to use the `cia-unix` command directly.  Thank you for the clear explanation & instructions (and pique my curiosity into [what makes Rust great](https://stackoverflow.blog/2020/01/20/what-is-rust-and-why-is-it-so-popular/)! 👀)
